"""empty message

Revision ID: 5fbe7410a0d1
Revises: 54541ad9ba8d
Create Date: 2023-05-18 14:01:17.606204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fbe7410a0d1'
down_revision = '54541ad9ba8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera', sa.String(), nullable=True),
    sa.Column('lights', sa.String(), nullable=True),
    sa.Column('audio', sa.String(), nullable=True),
    sa.Column('props', sa.String(), nullable=True),
    sa.Column('editing_software', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_equip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_user_equip_equipment_id_equipment')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_equip_user_id_user')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.drop_table('user_equip')
    op.drop_table('equipment')
    # ### end Alembic commands ###
